### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by bfred-it** [GhostText/GhostText#23]
- [ ] List all the features
- [ ] Show specific use cases
  - [ ] Edit Tumblr themes from the editor (once Cacodaimon/GhostTextForChrome/issues/26 is fixed)
  - [ ] Answer questions on StackOverflow
  - [ ] Reply on forums using BBcode
- [x] Add logo
