### ISSUE TITLE
Update the repo descriptions

### ISSUE THREAD

**Issue by bfred-it** [GhostText/GhostText#32]
* [ ] Update the GhostText for Sublime Text repo description to 
    > Use Sublime Text to write in your browser. Everything you type in the editor will be instantly updated in the browser (and vice versa).

* [ ] Update the GhostText for Chrome repo description to 
    > Use your text editor to write in Google Chrome. Everything you type in the editor will be instantly updated in the browser (and vice versa).

* [ ] Update the GhostText for Firefox repo description to 
    > Use your text editor to write in Firefox. Everything you type in the editor will be instantly updated in the browser (and vice versa).
