### ISSUE TITLE
META: merging projects into organization

### ISSUE THREAD

**Issue by bfred-it** [GhostText/GhostText#62]
Hello, picking up the conversation from https://github.com/Cacodaimon/GhostText-for-Chrome/issues/43 I want to suggest to merge the 4 repos as much as possible to avoid diluting our efforts and simplify issue creation.

I created a GH organization that would include the necessary repos: https://github.com/GhostText

It's currently filled with placeholders to better illustrate it

https://github.com/GhostText/GhostText 
https://github.com/GhostText/GhostText-for-Atom
https://github.com/GhostText/GhostText-for-SublimeText

Unfortunately the editors require direct access to the repos so we have to keep them separated, but we can still benefit this merge by disabling `issues` on both.

Here's the suggested order of operations and the suggested operator (me: 💙; @Cacodaimon: 💚)

- [x] 💙Push a **copy** of both GT-ST and GT-A to the temp repos
- [x] 💙 Point packagecontrol.io to the new repo (https://github.com/wbond/package_control_channel/pull/5408)
- [ ] 💚After packagecontrol move is verified to work, do this:
   - [x] 💙delete **GhostText/GhostText**
   - [x] 💚rename repo **GhostText-for-SublimeText** to **GhostText**  
   - [x] 💚transfer **Cacodaimon/GhostText** to the org **GhostText**
  this will let us keep the existing link **Cacodaimon/GhostText-for-SublimeText** point to **GhostText/GhostText** (main repo changes name, in short, while GH keeps a redirect. I just verified it to work) even though this repo won't actually contain GT-ST
- [ ] 💚 Point apm (Atom) to the new repo
- [x] 💚After apm's move is verified to work, do this as fast as possible
   - [x] 💚delete **GhostText/GhostText-for-Atom**
   - [x] 💚transfer **Cacodaimon/GhostText-for-Atom** to the org
- [x] 💙Manually merge GT-Ch and GT-FF into **GhostText/GhostText**, fully replacing its contents
- [x] 💙Empty your existing GT-Ch + GT-FF repos and keep a notice that they moved
- [ ] 💙Move all issues to **GhostText/GhostText** (which will already have existing GT-ST issues) and tag them appropriately (Chrome/Firefox/Atom/SublimeText)
- [x] 💙Leave only one issue open in remaining **Cacodaimon/GhostText-...** repos open in each: "DON'T OPEN ISSUES HERE"
- [ ] 💙💚 Review, close this issue, get beer

By following this:

- package managers will keep working
- all existing internet links will be kept or redirected
- issues will live in a single repo, tagged appropriately
- browsers will share similar code effortlessly

**Comment by Cacodaimon** [comment]
Maybe the transfer ownership o the repos will work, I would create a test repo and transfer the ownership?

![screenshot_2016-04-09_16-11-41](https://cloud.githubusercontent.com/assets/2429503/14404422/c9337ce2-fe6d-11e5-90c4-73f32561eecc.png)

**Comment by bfred-it** [comment]
GitHub seems to redirect `git clone` requests, so if both the package managers use git to pull the data we can just transfer them.

But if we just follow the suggested instructions we don't have to rely on "if"s. We'd still have to update the two managers eventually :)

**Comment by Cacodaimon** [comment]
@bfred-it 

Even if we screw it by the one or other way, we have five install per day in the average so a downtime of 1-2 hours wont kill us.

**Comment by bfred-it** [comment]
Alright! Either way you have access to the organization so you can start the transfer whenever you have time. Remember to only delete the GhostText/GhostText repo, not the other two, because THOSE will be the ones the the package managers access, not GhostText/GhostText

**Comment by bfred-it** [comment]
Ok, I opened a PR for packagecontrol in the meanwhile, you can do this already since GitHub will redirect current requests to the new transferred repo:

- [ ] rename repo **GhostText-for-SublimeText** to **GhostText**
- [ ] transfer **Cacodaimon/GhostText** to the org **GhostText**

Do it in this order because otherwise it won't let you transfer

**Comment by bfred-it** [comment]
Great! So far so good!

**Comment by bfred-it** [comment]
I've done almost all of my tasks, now we only need to move the apn package.

**Comment by Cacodaimon** [comment]
@bfred-it 

I will take care about this but I need some time reading about the atom package management again.

**Comment by bfred-it** [comment]
No problem! I was reading about it yesterday too and I couldn't find many answers

**Comment by Cacodaimon** [comment]
It seems that I never published the Atom prototoype to apm, thats makes the move to the org simple… .

**Comment by bfred-it** [comment]
Alright :)

I thought about moving all the Chrome issues, but there are quite a few, so I'll leave them there... until they get resolved. Any important ones will be migrated as needed.

This means that the move is done. ST's redirect is tracked directly here, if you want to subscribe: https://github.com/wbond/package_control_channel/pull/5408

Time for beer? 🍻 😁

**Comment by FichteFoll** [comment]
FYI, renaming repos requires the Package Control Channel to be updated because it uses the API to fetch data and github does not set up redirects for the API endpoints.

**Comment by bfred-it** [comment]
Thanks for the all the info @FichteFoll! I saw the org appear on my profile but I didn't realize that only I could see that. :) I'm public now!
